### ISSUE TITLE
Minimap button with non druid classes

### ISSUE THREAD

**Issue by NotKyros** [tekHudson/DruidBarClassic#11]
Disabling the "Show minimap button" option  does not disable the button on my non druid class characters.

**Comment by OnceWasPerfect** [comment]
I would like to add that changing any setting while on a non druid character seems to mess up settings on the druid character.  Adjusting the setting on the druid characters does correct them.

**Comment by tekHudson** [comment]
Thanks for the feedback. For now the quickfix was to disable addon loading on non druid characters.

Setting s are still on a per account basis as switching to per character was out of the scope of 1 nights work and I wanted to get that pushed.

**Comment by tekHudson** [comment]
Fixed by #13
