### ISSUE TITLE
"Bliz-Like" Text Display Inconsistencies and Suggested Improvements

### ISSUE THREAD

**Issue by Bugaloon** [tekHudson/DruidBarClassic#16]
DruidBarTextLeft displays with a slightly incorrect x axis offset. Changing Line 50 of `DruidBar.xml` from `<AbsDimension x="5" y="0"/>` to `<AbsDimension x="7" y="0"/>` fixes this.

`DruidBarTextRight` is set to the value of `ManaValues()` on Line 342 of `DruidBar.lua`, which returns both the current mana and maximum mana separated by a slash. On the Blizzard UI only the current mana is shown.

Changing Line 342 from `DruidBarTextRight:SetText(ManaValues());` to `DruidBarTextRight:SetText(floor(DruidBarKey.currentmana));` fixes this.

I suggest making a new way to handle the requests for mana values by the UI so that current mana can be retrieved separately from, or separated from maximum mana.

Before Image: https://i.imgur.com/l3vynL8.png

After Image: https://i.imgur.com/QYafDzN.png

**Comment by tekHudson** [comment]
Meged with #17
